# Generated by Django 3.2.8 on 2021-10-17 16:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("meetups", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetup",
            name="image",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to="images"
            ),
            preserve_default=False,
        ),
    ]
